@startuml

title 新生児ギャン泣きオンコール対応フローチャート
start

:泣く;

repeat;
  if (オムツが汚れている?) then (はい)
    :オムツを変える;
  else (いいえ)
    if (前回の授乳/ミルクから2時間以上経過している、\nもしくは舌を出す、\n乳房を探して首を振るなど空腹のサインが出ている?) then (はい)
      :授乳/ミルクを与える;
    else (いいえ)
      if (口をちゅぱちゅぱしている?) then (はい)
        :おしゃぶりを与える;
      else (いいえ)
      endif
      if (いきみやうなりがある、太鼓腹になっている?) then (はい)
        :げっぷを出させてみる;
      else (いいえ)
      endif
      :服やオムツを窮屈でないように整える;
      if (抱っこしている?) then (いいえ)
        :抱っこしてみる;
      else (はい)
        :布でくるむ;
        :気温(冬20~23度、夏26~28度が適温)に応じて\n服を1枚脱がす/着せる。湿度を上げる;
        :トントンしたり揺らす。歩いたり早足で足踏み・スクワットしてみる;
        :口元に手をあてて小刻みに動かし、アワワワワと言わせてみる;
        if (音を出せる環境にある?) then (はい)
          if (家に居る?) then (はい)
            :掃除機をかける;
          else (いいえ)
          endif
          :ホワイトノイズ、胎内音、雨音、ドライヤー音、\n換気扇音等をyoutubeやアレクサで聞かせる;
          :子守唄を歌う(ことりのうた、ゆりかごのうた、\nシューベルトの子守唄など);
          :数を数える(いーち、にー、さーん);
          :タケモトピアノのCM, 出前館のCM, ポイズン, カフカくん、狂言・詩吟、 \n トントントマトちゃん、7回攻撃前の野球応援音(風船音)などを\nyoutubeで聞かせる;
        else (いいえ)
        endif
        :ビニール袋をかしゃかしゃする;
        :顔に息をふきかける、うちわで扇ぐ;
        :手を握る;
        :自分が深呼吸する;
        :300秒放置する;
      endif
    endif
  endif
repeat while (泣き止んだ?) is (いいえ) not (はい)

stop

@enduml