@startuml

'test
title 新生児ギャン泣きオンコール対応フローチャート
start

:泣く;

repeat;
  if (オムツ/服/寝具が汚れている?) then (はい)
    :オムツ/服/寝具を替える;
  else (いいえ)
    if (前回の授乳/ミルクから2時間以上経過している、\nもしくは舌を出す、\n乳房を探して首を振るなど空腹のサインが出ている?) then (はい)
      :授乳/ミルクを与える;
    else (いいえ)
      if (いきみやうなりがある、太鼓腹になっている?\n顎を引き気道を確保しようとしている?) then (はい)
        :げっぷを出させてみる;
        if (便秘気味?) then (はい)
          :腹部マッサージや肛門刺激でうんちを促す;
        else (いいえ)
        endif
      else (いいえ)
      endif
      if (口をちゅぱちゅぱしている?) then (はい)
        :おしゃぶりを与える;
      else (いいえ)
      endif
      :服やオムツを窮屈でないように整える;
      :ラトル(ガラガラ)を振る;
      if (体温が38.0度以上/36.0度以下で衣服の枚数を変えても平熱に戻らない?\nor連続した嘔吐があったり呼吸が変?) then (はい)
        :小児科に連絡する;
        end
      else (いいえ)
      endif
      if (抱っこしてる?) then (いいえ)
        :抱っこしてみる;
      else (はい)
        :気温(冬20~23度、夏26~28度が適温)に応じて\n服を1枚脱がす/着せる。湿度を上げる;
        :(まだ使用していなければ)布でくるむ;
        :5分歩いて5~8分座る(輸送反応)。\nトントンしたり揺らす。\n早足で足踏み・スクワット・反復横跳び等をしてみる;
        :ホワイトノイズ、胎内音、雨音、心音、ドライヤー音、\n掃除機音、換気扇音、\n車のエンジン音(VTECサウンド、HONDA SOUND SITTER)等を\nyoutubeやアレクサで聞かせる;
        :タケモトピアノのCM, 出前館のCM, ポイズン, カフカくん、狂言・詩吟、 \n トントントマトちゃん、7回攻撃前の野球応援音(ジェット風船音)などを\nyoutubeで聞かせる;
        :子守唄(ことりのうた、ゆりかごのうた、\nシューベルトの子守唄など)を歌う;
        :ビニール袋をかしゃかしゃする;
        :顔に息をふきかける、うちわで扇ぐ;
        :手を握る;
        if (車を出せる?) then (はい)
          :ドライブする;
        else (いいえ)
        endif
        :自分が深呼吸する;
        :300秒放置する;
      endif
    endif
  endif
repeat while (泣き止んだ?) is (いいえ) not (はい)

stop

@enduml