@startuml
skinparam backgroundColor white
title 新生児ギャン泣き対応フローチャート
start

:泣く;

repeat;
  if (オムツ/服/寝具が汚れている?) then (はい)
    :オムツ/服/寝具を替える;
  else (いいえ)
    if (前回の授乳/ミルクから2時間以上経過している、\nもしくは舌を出す、\n乳房を探して首を振るなど空腹のサインが出ている?) then (はい)
      :授乳/ミルクを与える;
    else (いいえ)
      if (いきみやうなりがある、太鼓腹になっている?\n顎を引き気道を確保しようとしている?) then (はい)
        :げっぷを出させてみる;
        if (便秘気味?) then (はい)
          :腹部マッサージや肛門刺激でうんちを促す;
        else (いいえ)
        endif
      else (いいえ)
      endif
      if (口をちゅぱちゅぱしている?) then (はい)
        :おしゃぶりを与える;
      else (いいえ)
      endif
      :服やオムツを窮屈でないように整える;
      :鼻詰まり、髪や糸が身体の一部分に強く巻き付いていないかチェック;
      :頭、腹、足などを優しく掻いたりマッサージする;
      :ラトル(ガラガラ)を振って首や目線を動かす;
      :気温(冬20~23度、夏26~28度が適温)に応じて\n服を1枚脱がす/着せる。湿度を上げる;
      :(まだ使用していなければ)布でくるむ;
      if (体温が38.0度以上or36.0度未満で、\n衣服の枚数を変えても平熱に戻らない?\n連続した嘔吐があったり呼吸が変?) then (はい)
        :小児救急電話相談\n(#8000をプッシュ);
        kill
      else (いいえ)
      endif
      if (抱っこしてる?) then (いいえ)
        :抱っこしてみる;
      else (はい)
        :5分歩いて5~8分座る(輸送反応)。\nトントンしたり揺らす。\n早足で足踏み・スクワット・反復横跳び\n高い高い、低い低い等をしてみる;
        :抱っこの向き(縦・横)、角度を変えてみる;
        :ホワイトノイズ、胎内音、雨音、心音、ドライヤー音、\n掃除機音、換気扇音、車のエンジン音(VTECサウンド、HONDA SOUND SITTER)、\nタケモトピアノのCM, 出前館のCM, ポイズン, カフカくん、狂言・詩吟、 \n トントントマトちゃん、7回攻撃前の野球応援音(ジェット風船音)などを\nYoutubeやスマートスピーカーで聞かせる;
        :子守唄(ことりのうた、ゆりかごのうた、\nシューベルトの子守唄など)を歌う;
        :ビニール袋をかしゃかしゃする;
        :顔に息をふきかける、うちわで扇ぐ;
        :手を握る;
        :自分が深呼吸する;
        :300秒放置する;
      endif
    endif
  endif
repeat while (泣き止んだ?) is (いいえ) not (はい)

stop

@enduml
